# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BoxProto.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BoxProto.proto',
  package='com.woke.proto',
  serialized_pb='\n\x0e\x42oxProto.proto\x12\x0e\x63om.woke.proto\"0\n\x0f\x42oxLoginRequest\x12\x0e\n\x06\x62ox_id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"=\n\x10\x42oxLoginResponse\x12)\n\x06result\x18\x01 \x01(\x0e\x32\x19.com.woke.proto.BoxResult*\x1c\n\tBoxResult\x12\x0f\n\x0b\x42OX_SUCCESS\x10\x00')

_BOXRESULT = _descriptor.EnumDescriptor(
  name='BoxResult',
  full_name='com.woke.proto.BoxResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BOX_SUCCESS', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=147,
  serialized_end=175,
)

BoxResult = enum_type_wrapper.EnumTypeWrapper(_BOXRESULT)
BOX_SUCCESS = 0



_BOXLOGINREQUEST = _descriptor.Descriptor(
  name='BoxLoginRequest',
  full_name='com.woke.proto.BoxLoginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='box_id', full_name='com.woke.proto.BoxLoginRequest.box_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='com.woke.proto.BoxLoginRequest.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=34,
  serialized_end=82,
)


_BOXLOGINRESPONSE = _descriptor.Descriptor(
  name='BoxLoginResponse',
  full_name='com.woke.proto.BoxLoginResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='com.woke.proto.BoxLoginResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=84,
  serialized_end=145,
)

_BOXLOGINRESPONSE.fields_by_name['result'].enum_type = _BOXRESULT
DESCRIPTOR.message_types_by_name['BoxLoginRequest'] = _BOXLOGINREQUEST
DESCRIPTOR.message_types_by_name['BoxLoginResponse'] = _BOXLOGINRESPONSE

class BoxLoginRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOXLOGINREQUEST

  # @@protoc_insertion_point(class_scope:com.woke.proto.BoxLoginRequest)

class BoxLoginResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BOXLOGINRESPONSE

  # @@protoc_insertion_point(class_scope:com.woke.proto.BoxLoginResponse)


# @@protoc_insertion_point(module_scope)
