# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NotifyProto.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NotifyProto.proto',
  package='com.woke.proto',
  serialized_pb='\n\x11NotifyProto.proto\x12\x0e\x63om.woke.proto\"I\n\x11NotifyMessagePlay\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x10\n\x08\x61uto_run\x18\x02 \x01(\t\x12\x11\n\tcycle_run\x18\x03 \x01(\t\",\n\x19NotifyMessageSpeechString\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x14NotifyMessageEventUp\x12\x0f\n\x07message\x18\x01 \x01(\x05*\"\n\x0cNotifyResult\x12\x12\n\x0eNOTIFY_SUCCESS\x10\x00')

_NOTIFYRESULT = _descriptor.EnumDescriptor(
  name='NotifyResult',
  full_name='com.woke.proto.NotifyResult',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOTIFY_SUCCESS', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=199,
  serialized_end=233,
)

NotifyResult = enum_type_wrapper.EnumTypeWrapper(_NOTIFYRESULT)
NOTIFY_SUCCESS = 0



_NOTIFYMESSAGEPLAY = _descriptor.Descriptor(
  name='NotifyMessagePlay',
  full_name='com.woke.proto.NotifyMessagePlay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='com.woke.proto.NotifyMessagePlay.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auto_run', full_name='com.woke.proto.NotifyMessagePlay.auto_run', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cycle_run', full_name='com.woke.proto.NotifyMessagePlay.cycle_run', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=110,
)


_NOTIFYMESSAGESPEECHSTRING = _descriptor.Descriptor(
  name='NotifyMessageSpeechString',
  full_name='com.woke.proto.NotifyMessageSpeechString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='com.woke.proto.NotifyMessageSpeechString.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=112,
  serialized_end=156,
)


_NOTIFYMESSAGEEVENTUP = _descriptor.Descriptor(
  name='NotifyMessageEventUp',
  full_name='com.woke.proto.NotifyMessageEventUp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='com.woke.proto.NotifyMessageEventUp.message', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=158,
  serialized_end=197,
)

DESCRIPTOR.message_types_by_name['NotifyMessagePlay'] = _NOTIFYMESSAGEPLAY
DESCRIPTOR.message_types_by_name['NotifyMessageSpeechString'] = _NOTIFYMESSAGESPEECHSTRING
DESCRIPTOR.message_types_by_name['NotifyMessageEventUp'] = _NOTIFYMESSAGEEVENTUP

class NotifyMessagePlay(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NOTIFYMESSAGEPLAY

  # @@protoc_insertion_point(class_scope:com.woke.proto.NotifyMessagePlay)

class NotifyMessageSpeechString(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NOTIFYMESSAGESPEECHSTRING

  # @@protoc_insertion_point(class_scope:com.woke.proto.NotifyMessageSpeechString)

class NotifyMessageEventUp(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NOTIFYMESSAGEEVENTUP

  # @@protoc_insertion_point(class_scope:com.woke.proto.NotifyMessageEventUp)


# @@protoc_insertion_point(module_scope)
